site_name: Santos Docs
theme: 
  name: material
  features:
    - content.code.annotate #
markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - meta
  - toc:
      permalink: True
  - markdown_include.include:
      base_path: docs
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
    - search
    - awesome-pages
nav:
  - Home: index.md
  - Labs Kubernetes:
        - Minikube:
            - ... | flat |*/minikube/*.md
        - Azure Kubernetes Service:
            - labs_kubernetes/azure/labs1.md
        - Graphana:
            - labs_kubernetes/helm/graphana_prometheus.md

  - Celery & Fast API Labs:
        - ... | flat | celeryfastapi/*.md

  - Google Maps Scrapper:
        - GoogleMapsScrapper.md
  - Microservices with Docker: cbir_project.md
  - Lists In Haskell: haskell.md
  - Versions a Git Clone: versions.md